# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.4
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: my@mail.com
author_name: John Doe
cloud_provider: none
contract_name: hello_dutch
deployment_language: python
preset_name: production
project_name: AlgoDutch

