# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.5
_src_path: gh:algorandfoundation/algokit-python-template
author_email: my@mail.com
author_name: John Doe
contract_name: hello_dutch
deployment_language: python
preset_name: production
project_name: AlgoDutch-contracts

